### ISSUE TITLE
how to use animation?

### ISSUE THREAD

**Issue by TheLoyalCruel** [ShamylZakariya/StickyHeaders#34]
Hi
I use this lib to animate recyclerview : [https://github.com/wasabeef/recyclerview-animators](url)
but when i use SectioningAdapter i get this cast error : 

`Caused by: java.lang.ClassCastException: StickyHeaderLayoutManager must be used with a RecyclerView where the adapter is a kind of SectioningAdapter
                                                                       at org.zakariya.stickyheaders.StickyHeaderLayoutManager.onAdapterChanged(StickyHeaderLayoutManager.java:103)
                                                                       at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:920)
                                                                       at android.support.v7.widget.RecyclerView.setAdapter(RecyclerView.java:877)
                                                                       at com.farahefaz.app.activities.SpecActivity.onCreate(SpecActivity.java:98)
                                                                       at android.app.Activity.performCreate(Activity.java:6285)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:234) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5526) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

is there any other way to animate this StickyHeaders?
thanks in advance...

**Comment by ShamylZakariya** [comment]
`StickyHeaderLayoutManager` requires the use of `SectioningAdapter` to work. That's just how it is. 

You'll note that the `recyclerview-animators` project is supplying adapters that do the fancy work. My suggestion to you is to write a custom `SectioningAdapter` subclass, and adapt whatever animation techniques `recyclerview-animators` is using.
