### ISSUE TITLE
animateLayoutChanges -> exception

### ISSUE THREAD

**Issue by adrianaisemberg** [ShamylZakariya/StickyHeaders#38]
java.lang.IllegalArgumentException: **Scrapped or attached views may not be recycled. isScrap:false isAttached:true**
             at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5420)
             at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5364)
             at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleView(RecyclerView.java:7698)
             at org.zakariya.stickyheaders.StickyHeaderLayoutManager.recycleViewsOutOfBounds(StickyHeaderLayoutManager.java:624)
             at org.zakariya.stickyheaders.StickyHeaderLayoutManager.scrollVerticallyBy(StickyHeaderLayoutManager.java:435)
             at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1640)
             at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2759)
             at android.view.View.dispatchTouchEvent(View.java:10023)

**Comment by adrianaisemberg** [comment]
I'd like to see new/deleted items animated.

**Comment by ShamylZakariya** [comment]
Can you provide sample code to replicate this?

**Comment by adrianaisemberg** [comment]
It happens also when using a RecyclerView with the default adapter. Seems
like it's not an issue with your library.
Please feel free to close the issue...




Adrian Aisemberg

Get Tapet for Android
<https://play.google.com/store/apps/details?id=com.sharpregion.tapet>

**Comment by ShamylZakariya** [comment]
Ok, cool. I've seen a *lot* of issues with RecyclerView crashing when certain types of changes happen during a scroll (while the user's finger is still touching the screen). The newer recyclerview 25.0.1 seems to fix some of these.
