### ISSUE TITLE
Error: "Scrapped or attached views may not be recycled" with LinearLayoutManager

### ISSUE THREAD

**Issue by jomapp** [ShamylZakariya/StickyHeaders#48]
Hi, I need to use the LinearLayoutManager instead of StickyHeaderLayoutManager. But while using the LinearLayoutManager it's constantly crashing with the following error message:

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: de.munichsdorfer.timelog, PID: 24648
                                                                          java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                              at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5659)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5603)
                                                                              at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:277)
                                                                              at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
                                                                              at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
                                                                              at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
                                                                              at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

How can I fix this issue? Thank you very much in advance! :)

**Comment by pierrediderot** [comment]
+1

**Comment by pierrediderot** [comment]
@jomapp I solved this problem using `layoutManager="org.zakariya.stickyheaders.StickyHeaderLayoutManager"`

**Comment by EzimetYusup** [comment]
@pierrediderot  the problem is when  trying to use SectioningAdapter with LinearLayoutManager not with StickyHeaderLayoutManager, @ShamylZakariya do you have any idea about this issue?

**Comment by EzimetYusup** [comment]
@jomapp when is it crashing for you?

**Comment by EzimetYusup** [comment]
@jomapp  could you try this code? create custom LinearLayoutManager and override this method
```java 
   @Override
    public void collectAdjacentPrefetchPositions(int dx, int dy, RecyclerView.State state, LayoutPrefetchRegistry layoutPrefetchRegistry) {
        try {
            super.collectAdjacentPrefetchPositions(dx, dy, state, layoutPrefetchRegistry);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        }

    }
```

**Comment by ShamylZakariya** [comment]
Can you provide a simple demo app which exhibits the behavior? I never saw this during development.

**Comment by EzimetYusup** [comment]
@ShamylZakariya  me too, I saw it only on Crashlytics.

**Comment by jmaricic** [comment]
I'm having the same issue... This is what my adapter looks like:

public class WalletAdapter extends SectioningAdapter {

    static final boolean USE_DEBUG_APPEARANCE = false;


    private List<Transaction> transactions;
    private List<Section> sections = new ArrayList<>();

    public WalletAdapter() {
    }

    private class Section {
        String alpha;
        List<Transaction> transactions = new ArrayList<>();
    }

    public List<Transaction> getTransactions() {
        return transactions;
    }

    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
        sections.clear();

        String mDate = "31.12.2222";

        Section currentSection = null;
        for (Transaction transaction : transactions) {
            String date = parseDate(transaction.getCreatedDate());
            if (!date.equals(mDate)) {
                if (currentSection != null) {
                    sections.add(currentSection);
                }

                currentSection = new Section();
                mDate = date;
                currentSection.alpha = String.valueOf(mDate);
            }

            if (currentSection != null) {
                currentSection.transactions.add(transaction);
            }
        }

        sections.add(currentSection);
        notifyAllSectionsDataSetChanged();
    }

    private String parseDate(Date date) {
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
        String formattedDate = "";
        formattedDate = df.format(date);
        return formattedDate;
    }

    @Override
    public int getNumberOfSections() {
        return sections.size();
    }

    @Override
    public boolean doesSectionHaveHeader(int sectionIndex) {
        return sectionIndex == 0 || !parseDate(transactions.get(sectionIndex).getCreatedDate()).equals(parseDate(transactions.get(sectionIndex - 1).getCreatedDate()));
    }

    @Override
    public boolean doesSectionHaveFooter(int sectionIndex) {
        return false;
    }

    @Override
    public int getNumberOfItemsInSection(int sectionIndex) {
        return sections.get(sectionIndex).transactions.size();
    }

    @Override
    public ItemViewHolder onCreateItemViewHolder(ViewGroup parent, int itemUserType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        View v = inflater.inflate(R.layout.wallet_item, parent, false);
        return new ItemViewHolder(v);
    }

    @Override
    public HeaderViewHolder onCreateHeaderViewHolder(ViewGroup parent, int headerUserType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        View v = inflater.inflate(R.layout.wallet_header, parent, false);
        return new HeaderViewHolder(v);
    }

    @Override
    public void onBindItemViewHolder(SectioningAdapter.ItemViewHolder viewHolder, int sectionIndex, int itemIndex, int itemType) {
        super.onBindItemViewHolder(viewHolder, sectionIndex, itemIndex, itemType);
        Section section = sections.get(sectionIndex);
        ItemViewHolder holder = (ItemViewHolder) viewHolder;
        Transaction transaction = section.transactions.get(itemIndex);
        holder.description.setText(transaction.getDescription());
        holder.ammount.setText(String.valueOf(transaction.getAmount()));
        holder.time.setText(parseDate(transaction.getCreatedDate()));
        holder.total.setText(String.format(Locale.getDefault(), "%.3f", transaction.getNewCredits()));
    }


    @Override
    public void onBindHeaderViewHolder(SectioningAdapter.HeaderViewHolder viewHolder, int sectionIndex, int headerType) {
        super.onBindHeaderViewHolder(viewHolder, sectionIndex, headerType);
        Section s = sections.get(sectionIndex);
        HeaderViewHolder hvh = (HeaderViewHolder) viewHolder;

        if (USE_DEBUG_APPEARANCE) {
            hvh.itemView.setBackgroundColor(0x55ffffff);
            hvh.dateHeader.setText(pad(sectionIndex * 2) + s.alpha);
        } else {
            hvh.dateHeader.setText(s.alpha);
        }
    }

    private String pad(int spaces) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < spaces; i++) {
            b.append(' ');
        }
        return b.toString();
    }

    public class HeaderViewHolder extends SectioningAdapter.HeaderViewHolder {

        TextView dateHeader;

        public HeaderViewHolder(View itemView) {
            super(itemView);
            dateHeader = (TextView) itemView.findViewById(R.id.date);
        }
    }

    public class ItemViewHolder extends SectioningAdapter.ItemViewHolder {

        TextView description;
        TextView time;
        TextView ammount;
        TextView total;

        public ItemViewHolder(View itemView) {
            super(itemView);
            description = (TextView) itemView.findViewById(R.id.description);
            time = (TextView) itemView.findViewById(R.id.time);
            ammount = (TextView) itemView.findViewById(R.id.ammount);
            total = (TextView) itemView.findViewById(R.id.new_credits);
        }
    }
}

**Comment by matheuskiser** [comment]
@ShamylZakariya, @EzimetYusup, I am also getting the same error when only using HeaderViews and not Footers. The solution was not adding the GhostView to the parent ViewGroup in SectioningAdapter.onCreateGhostHeaderViewHolder. https://github.com/ShamylZakariya/StickyHeaders/pull/70.

**Comment by DanielNovak** [comment]
Are you maybe using `animateLayoutChanges` on that RecyclerView? We had the same issue and it was because we (unintentionally) had this flag set. https://stackoverflow.com/questions/26477660/recyclerview-crashes-when-scrapped-or-attached-views-may-not-be-recycled/26479862#26479862

**Comment by matheuskiser** [comment]
@DanielNovak I'm not using `animateLayoutChanges`.

**Comment by pierrediderot** [comment]
I only use StickyHeaderLayoutManager, because when I use LinearLayoutManager and I use the crazy scroll, this error happens.

**Comment by namnl** [comment]
It took me two days but could not get around this, in the end I found this post:

When setting the layout manager you can simply call
mGridLayoutManager.setItemPrefetchEnabled(false);
It made the error go away for me. Hope it will be useful for someone.
